name: Docs to PDF
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    paths:
      - 'markdown/**.md'

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdown
          output_dir: action-output
          build_html: true
      - uses: actions/upload-artifact@v1
        with:
          name: docs
          path: action-output
