name: Markdown to HTML
on:
  workflow_dispatch:
  push:
    branches:
      - working
    paths:
      - 'markdown/**.md'

jobs:
  converttopdf:
    name: Build HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: markdown
          build_html: true
          build_pdf: false
          theme: theme.css
      - uses: actions/upload-artifact@v1
        with:
          name: HTML
          path: action-output
